#!/usr/bin/env python3
import json
from research_common import OUT

def pct(n,d): return round(100*n/d,1) if d else 0

def main():
    s=json.loads((OUT/'corpus_research_statistics.json').read_text(encoding='utf-8'))
    de=s['active_articles_by_direction']['DE-RAR']; rar=s['active_articles_by_direction']['RAR-DE']; att_de=s['de_rar_records_with_inventory_guided_attestations']; att_rar=s['rar_de_records_attested_inside_de_rar']; sem=s['diachronic_semantic_context_signal_counts']; any_internal=sem.get('internal_form_attestation_only',0)+sem.get('internal_reciprocal_documentary_support',0); total_sem=s['diachronic_semantic_context_candidates']; recip_sem=sem.get('internal_reciprocal_documentary_support',0); tri=s['residual_span_triage_profile_class_counts']; grades=s['residual_recovery_evidence_grade_counts']
    text=f'''# Rarámuri Histórico Digital — corte de investigación interna\n\n**Generado:** 2026-08-13  \n**Revisión humana de relaciones:** **0**.\n\n## Resultados computacionales\n\n- artículos activos: **{s['active_articles_total']}** ({de} DE–RAR; {rar} RAR–DE);\n- componentes RAR–DE: **{s['rar_de_component_attestations']}**; claves gráficas conservadoras únicas: **{s['rar_de_unique_graphic_keys']}**;\n- atestiguaciones DE–RAR guiadas por el inventario RAR–DE: **{s['de_rar_inventory_guided_attestations']}**;\n- registros DE–RAR con alguna atestiguación guiada: **{att_de}/{de} ({pct(att_de,de)}%)**;\n- registros RAR–DE reatestiguados dentro de DE–RAR: **{att_rar}/{rar} ({pct(att_rar,rar)}%)**;\n- candidatos de concordancia interna: **{s['internal_concordance_candidates']}**; con apoyo alemán recíproco: **{s['internal_reciprocal_german_support_candidates']} ({pct(s['internal_reciprocal_german_support_candidates'],s['internal_concordance_candidates'])}%)**;\n- segmentos residuales DE–RAR triados: **{s['residual_span_triage_candidates']}** = {tri.get('strong_raramuri_profile_signal',0)} señal fuerte de perfil, {tri.get('possible_raramuri_profile_signal',0)} posible, {tri.get('german_context_profile_signal',0)} contexto alemán y {tri.get('mixed_or_uncertain_profile',0)} mixtos/inciertos;\n- cola deduplicada de recuperación: **{s['residual_recovery_candidate_groups']} grupos** a partir de {s['residual_recovery_source_profile_signal_spans']} spans; grados A/B/C/D = **{grades.get('A_machine_documentary_signal',0)}/{grades.get('B_machine_documentary_signal',0)}/{grades.get('C_machine_profile_signal',0)}/{grades.get('D_machine_possible_profile_signal',0)}**; grupos recurrentes en ≥2 artículos DE–RAR: **{s['residual_recovery_cross_entry_recurrent_groups']}**;\n- grupos de variantes explícitas: **{s['explicit_source_variant_groups']}**; colisiones gráficas conservadoras: **{s['normalized_graphic_collision_groups']}**;\n- candidatos diacrónicos con alguna señal interna de Steffel: **{any_internal}/{total_sem} ({pct(any_internal,total_sem)}%)**; con apoyo interno recíproco: **{recip_sem}/{total_sem} ({pct(recip_sem,total_sem)}%)**.\n\n## Límite interpretativo\n\nLas proporciones anteriores son **cobertura y señales computacionales**, no tasas de validación. El triage residual usa perfiles documentales de n-gramas y cercanía gráfica para ordenar inspección; no realiza identificación automática de lengua ni crea lexemas. Los grupos de recuperación son candidatos deduplicados y sus grados A–D sólo expresan fuerza de evidencia de máquina. La concordancia interna registra coaparición documental entre las dos direcciones de Steffel. Ninguna de estas capas afirma cognación, continuidad histórica, identidad dialectal ni validación humana.\n'''
    (OUT/'RESEARCH_SNAPSHOT.md').write_text(text,encoding='utf-8')
if __name__=='__main__': main()
