#!/usr/bin/env python3
import json
from collections import Counter
from research_common import ROOT,OUT,rows,active,norm,split_components,dump

def main():
    rr=[r for r in rows() if active(r)]; de=[r for r in rr if r.get('direction')=='DE-RAR']; rar=[r for r in rr if r.get('direction')=='RAR-DE']
    forms=[c for r in rar for c in split_components(r.get('headword_diplomatic',''))]; keys=[norm(x) for x in forms]
    att=json.loads((OUT/'de_rar_inventory_guided_attestations_summary.json').read_text(encoding='utf-8')); tri=json.loads((OUT/'de_rar_residual_span_triage_summary.json').read_text(encoding='utf-8')); con=json.loads((OUT/'internal_concordance_summary.json').read_text(encoding='utf-8')); var=json.loads((OUT/'historical_variant_index_summary.json').read_text(encoding='utf-8')); sem=json.loads((OUT/'diachronic_semantic_context_queue_summary.json').read_text(encoding='utf-8'))
    stats={'dataset':'raramuri-historico-steffel-1809','generated':'2026-08-13','active_articles_total':len(rr),'active_articles_by_direction':{'DE-RAR':len(de),'RAR-DE':len(rar)},'rar_de_component_attestations':len(forms),'rar_de_unique_graphic_keys':len(set(keys)),'rar_de_unique_surface_forms':len(set(forms)),'repeated_graphic_keys_top':[{'graphic_key':k,'attestations':n} for k,n in Counter(keys).most_common(30) if n>1],'de_rar_inventory_guided_attestations':att['candidate_count'],'de_rar_records_with_inventory_guided_attestations':att['de_rar_records_represented'],'rar_de_records_attested_inside_de_rar':att['rar_de_records_represented'],'internal_concordance_candidates':con['candidate_count'],'internal_reciprocal_german_support_candidates':con['reciprocal_german_support_count'],'residual_de_rar_span_candidates_low_machine':att['residual_span_candidates_low_machine'],'residual_span_triage_candidates':tri['candidate_count'],'residual_span_triage_profile_class_counts':tri['profile_class_counts'],'residual_span_triage_priority_tier_counts':tri['review_priority_tier_counts'],'residual_span_triage_method':tri['method'],'residual_span_triage_automatic_language_identification':False,'residual_span_triage_automatic_lexeme_creation':False,'explicit_source_variant_groups':var['explicit_source_variant_group_count'],'normalized_graphic_collision_groups':var['normalized_graphic_collision_group_count'],'diachronic_semantic_context_candidates':sem['candidate_count'],'diachronic_semantic_context_signal_counts':sem['signal_counts'],'human_reviewed_internal_relations':0,'human_reviewed_diachronic_relations':0,'scope_note':'Derived documentary/machine counts; no validated lexical, language-identification, semantic, etymological or historical relation is asserted.'}
    dump(OUT/'corpus_research_statistics.json',stats)
    public={'generated':stats['generated'],'active_articles_total':len(rr),'active_articles_by_direction':stats['active_articles_by_direction'],'rar_de_unique_graphic_keys':stats['rar_de_unique_graphic_keys'],'inventory_guided_attestations':att['candidate_count'],'internal_concordance_candidates':con['candidate_count'],'reciprocal_german_support_candidates':con['reciprocal_german_support_count'],'residual_span_triage':{'candidate_count':tri['candidate_count'],'profile_class_counts':tri['profile_class_counts'],'priority_tier_counts':tri['review_priority_tier_counts'],'automatic_language_identification':False,'automatic_lexeme_creation':False},'explicit_variant_groups':var['explicit_source_variant_group_count'],'graphic_collision_groups':var['normalized_graphic_collision_group_count'],'diachronic_semantic_context_signals':sem['signal_counts'],'human_reviewed_relations':0,'warning':'Machine/documentary candidates and profile signals, not validated linguistic relations or automatic language identifications.'}
    dump(ROOT/'public/data/research-summary.json',public); print(json.dumps(stats,ensure_ascii=False))
if __name__=='__main__': main()
