#!/usr/bin/env python3
import json
from collections import Counter
from research_common import ROOT,OUT,rows,active,norm,split_components,dump

def load(name): return json.loads((OUT/name).read_text(encoding='utf-8'))

def main():
    rr=[r for r in rows() if active(r)];de=[r for r in rr if r.get('direction')=='DE-RAR'];rar=[r for r in rr if r.get('direction')=='RAR-DE']
    forms=[c for r in rar for c in split_components(r.get('headword_diplomatic',''))];keys=[norm(x) for x in forms]
    att=load('de_rar_inventory_guided_attestations_summary.json');tri=load('de_rar_residual_span_triage_summary.json');rec=load('de_rar_residual_recovery_queue_summary.json');fam=load('graphic_family_hypotheses_summary.json');gctx=load('graphic_context_associations_summary.json');ameke=load('ameke_constellation_summary.json');perm=load('ameke_permutation_tests_summary.json');rob=load('ameke_ugameke_robustness_controls_summary.json');con=load('internal_concordance_summary.json');var=load('historical_variant_index_summary.json');sem=load('diachronic_semantic_context_queue_summary.json')
    stats={'dataset':'raramuri-historico-steffel-1809','generated':'2026-08-13','active_articles_total':len(rr),'active_articles_by_direction':{'DE-RAR':len(de),'RAR-DE':len(rar)},'rar_de_component_attestations':len(forms),'rar_de_unique_graphic_keys':len(set(keys)),'rar_de_unique_surface_forms':len(set(forms)),'repeated_graphic_keys_top':[{'graphic_key':k,'attestations':n} for k,n in Counter(keys).most_common(30) if n>1],
    'de_rar_inventory_guided_attestations':att['candidate_count'],'de_rar_records_with_inventory_guided_attestations':att['de_rar_records_represented'],'rar_de_records_attested_inside_de_rar':att['rar_de_records_represented'],'internal_concordance_candidates':con['candidate_count'],'internal_reciprocal_german_support_candidates':con['reciprocal_german_support_count'],
    'residual_de_rar_span_candidates_low_machine':att['residual_span_candidates_low_machine'],'residual_span_triage_candidates':tri['candidate_count'],'residual_span_triage_profile_class_counts':tri['profile_class_counts'],'residual_span_triage_priority_tier_counts':tri['review_priority_tier_counts'],'residual_span_triage_method':tri['method'],'residual_span_triage_automatic_language_identification':False,'residual_span_triage_automatic_lexeme_creation':False,
    'residual_recovery_candidate_groups':rec['unique_recovery_candidate_groups'],'residual_recovery_source_profile_signal_spans':rec['source_profile_signal_spans'],'residual_recovery_evidence_grade_counts':rec['evidence_grade_counts'],'residual_recovery_cross_entry_recurrent_groups':rec['cross_entry_recurrent_groups'],'residual_recovery_automatic_language_identification':False,'residual_recovery_automatic_lexeme_creation':False,
    'graphic_family_grade_a_seed_count':fam['grade_a_seed_count'],'graphic_family_hypothesis_count':fam['family_hypothesis_count'],'graphic_families_with_neighbors':fam['families_with_neighbors'],'graphic_family_total_neighbor_links':fam['total_neighbor_links'],'recurrent_graphic_prefix_pattern_count':fam['recurrent_prefix_pattern_count'],'recurrent_graphic_suffix_pattern_count':fam['recurrent_suffix_pattern_count'],'graphic_family_automatic_morphological_analysis':False,'graphic_family_automatic_morpheme_assignment':False,
    'graphic_context_key_universe_count':gctx['context_key_universe_count'],'graphic_context_pattern_association_count':gctx['pattern_association_count'],'graphic_context_family_association_count':gctx['family_association_count'],'graphic_context_patterns_with_enriched_tokens':gctx['patterns_with_enriched_tokens'],'graphic_context_families_with_enriched_tokens':gctx['families_with_enriched_tokens'],'graphic_context_robust_pattern_token_association_count':gctx['robust_pattern_token_association_count'],'graphic_context_robust_pattern_proxy_association_count':gctx['robust_pattern_proxy_association_count'],'graphic_context_global_word_shape_proxy_counts':gctx['global_german_word_shape_proxy_counts'],'graphic_context_method':gctx['method'],'graphic_context_automatic_semantic_classification':False,'graphic_context_automatic_part_of_speech_tagging':False,
    'ameke_constellation_member_count':ameke['member_count'],'ameke_inclusive_suffix_member_counts':ameke['inclusive_suffix_member_counts'],'ameke_exclusive_suffix_member_counts':ameke['exclusive_suffix_member_counts'],'ameke_members_internally_reattested':ameke['members_internally_reattested'],'ameke_members_with_internal_reciprocal_support':ameke['members_with_internal_reciprocal_support'],'ameke_exact_shared_stripped_base_group_count':ameke['exact_shared_stripped_base_group_count'],'ameke_base_contrast_candidate_count':ameke['base_contrast_candidate_count'],'ameke_exact_base_contrast_pair_count':ameke['exact_base_contrast_pair_count'],'ameke_edit_distance_one_base_contrast_pair_count':ameke['edit_distance_one_base_contrast_pair_count'],'ameke_contrast_review_priority_tier_counts':ameke['contrast_review_priority_tier_counts'],'ameke_automatic_morphological_analysis':False,'ameke_automatic_morpheme_assignment':False,'ameke_automatic_semantic_classification':False,'ameke_automatic_paradigm_inference':False,
    'ameke_permutation_iterations':perm['permutation_iterations'],'ameke_permutation_random_seed':perm['random_seed'],'ameke_permutation_context_count':perm['context_count'],'ameke_permutation_cell_test_count':perm['cell_test_count'],'ameke_permutation_omnibus_chi_square':perm['omnibus_chi_square_observed'],'ameke_permutation_omnibus_cramers_v_descriptive':perm['omnibus_cramers_v_descriptive'],'ameke_permutation_omnibus_empirical_p':perm['omnibus_empirical_permutation_p'],'ameke_permutation_raw_p_le_0_05_count':perm['raw_empirical_p_le_0_05_count'],'ameke_permutation_bh_fdr_q_le_0_05_count':perm['bh_fdr_q_le_0_05_count'],'ameke_permutation_maxT_fwer_p_le_0_05_count':perm['maxT_fwer_p_le_0_05_count'],'ameke_permutation_conservative_signal_count':perm['conservative_permutation_signal_count'],'ameke_permutation_conservative_signals':perm['conservative_permutation_signals'],'ameke_permutation_method':perm['null_model'],'ameke_permutation_human_reviewed':False,'ameke_permutation_automatic_morphological_analysis':False,'ameke_permutation_automatic_semantic_classification':False,
    'ameke_robustness_target_class':rob['target_graphic_class'],'ameke_robustness_target_proxy':rob['target_german_context_proxy'],'ameke_robustness_permutation_scheme_count':rob['permutation_scheme_count'],'ameke_robustness_permutation_test_count':rob['permutation_test_count'],'ameke_robustness_positive_p_le_0_05_test_count':rob['positive_p_le_0_05_permutation_test_count'],'ameke_robustness_all_context_schemes_p_le_0_05':rob['all_primary_context_permutation_schemes_p_le_0_05'],'ameke_robustness_all_member_binary_schemes_p_le_0_05':rob['all_member_binary_permutation_schemes_p_le_0_05'],'ameke_robustness_leave_one_target_context_min':rob['leave_one_target_member_out']['context_rate_difference_min'],'ameke_robustness_leave_one_target_nonpositive_count':rob['leave_one_target_member_out']['context_nonpositive_count'],'ameke_robustness_leave_one_page10_context_min':rob['leave_one_page10_block_out']['context_rate_difference_min'],'ameke_robustness_leave_one_page10_nonpositive_count':rob['leave_one_page10_block_out']['context_nonpositive_count'],'ameke_robustness_target_members_with_proxy':rob['target_signal_concentration']['target_members_with_proxy'],'ameke_robustness_target_proxy_context_count':rob['target_signal_concentration']['target_proxy_context_count'],'ameke_robustness_max_single_member_proxy_share':rob['target_signal_concentration']['share_of_target_proxy_contexts_in_largest_member'],
    'explicit_source_variant_groups':var['explicit_source_variant_group_count'],'normalized_graphic_collision_groups':var['normalized_graphic_collision_group_count'],'diachronic_semantic_context_candidates':sem['candidate_count'],'diachronic_semantic_context_signal_counts':sem['signal_counts'],'human_reviewed_internal_relations':0,'human_reviewed_diachronic_relations':0,'scope_note':'Derived documentary/machine counts and permutation-calibrated graphic-context dependence; no validated lexical, language-identification, morphological, grammatical, semantic, etymological or historical relation is asserted.'}
    dump(OUT/'corpus_research_statistics.json',stats)
    public={'generated':stats['generated'],'active_articles_total':len(rr),'active_articles_by_direction':stats['active_articles_by_direction'],'rar_de_unique_graphic_keys':stats['rar_de_unique_graphic_keys'],'inventory_guided_attestations':att['candidate_count'],'internal_concordance_candidates':con['candidate_count'],'reciprocal_german_support_candidates':con['reciprocal_german_support_count'],
    'residual_span_triage':{'candidate_count':tri['candidate_count'],'profile_class_counts':tri['profile_class_counts'],'priority_tier_counts':tri['review_priority_tier_counts'],'automatic_language_identification':False,'automatic_lexeme_creation':False},
    'residual_recovery_queue':{'unique_candidate_groups':rec['unique_recovery_candidate_groups'],'source_profile_signal_spans':rec['source_profile_signal_spans'],'evidence_grade_counts':rec['evidence_grade_counts'],'cross_entry_recurrent_groups':rec['cross_entry_recurrent_groups'],'automatic_language_identification':False,'automatic_lexeme_creation':False},
    'graphic_family_hypotheses':{'grade_a_seed_count':fam['grade_a_seed_count'],'family_hypothesis_count':fam['family_hypothesis_count'],'families_with_neighbors':fam['families_with_neighbors'],'total_neighbor_links':fam['total_neighbor_links'],'prefix_pattern_count':fam['recurrent_prefix_pattern_count'],'suffix_pattern_count':fam['recurrent_suffix_pattern_count'],'automatic_morphological_analysis':False,'automatic_morpheme_assignment':False},
    'graphic_context_associations':{'context_key_universe_count':gctx['context_key_universe_count'],'pattern_association_count':gctx['pattern_association_count'],'family_association_count':gctx['family_association_count'],'patterns_with_enriched_tokens':gctx['patterns_with_enriched_tokens'],'families_with_enriched_tokens':gctx['families_with_enriched_tokens'],'robust_pattern_token_association_count':gctx['robust_pattern_token_association_count'],'robust_pattern_proxy_association_count':gctx['robust_pattern_proxy_association_count'],'global_german_word_shape_proxy_counts':gctx['global_german_word_shape_proxy_counts'],'method':gctx['method'],'automatic_semantic_classification':False,'automatic_part_of_speech_tagging':False},
    'ameke_constellation':{'member_count':ameke['member_count'],'inclusive_suffix_member_counts':ameke['inclusive_suffix_member_counts'],'exclusive_suffix_member_counts':ameke['exclusive_suffix_member_counts'],'members_internally_reattested':ameke['members_internally_reattested'],'members_with_internal_reciprocal_support':ameke['members_with_internal_reciprocal_support'],'exact_shared_stripped_base_group_count':ameke['exact_shared_stripped_base_group_count'],'base_contrast_candidate_count':ameke['base_contrast_candidate_count'],'exact_base_contrast_pair_count':ameke['exact_base_contrast_pair_count'],'edit_distance_one_base_contrast_pair_count':ameke['edit_distance_one_base_contrast_pair_count'],'automatic_morphological_analysis':False,'automatic_morpheme_assignment':False,'automatic_semantic_classification':False,'automatic_paradigm_inference':False},
    'ameke_permutation_controls':{'iterations':perm['permutation_iterations'],'random_seed':perm['random_seed'],'context_count':perm['context_count'],'cell_test_count':perm['cell_test_count'],'omnibus_chi_square_observed':perm['omnibus_chi_square_observed'],'omnibus_cramers_v_descriptive':perm['omnibus_cramers_v_descriptive'],'omnibus_empirical_permutation_p':perm['omnibus_empirical_permutation_p'],'raw_p_le_0_05_count':perm['raw_empirical_p_le_0_05_count'],'bh_fdr_q_le_0_05_count':perm['bh_fdr_q_le_0_05_count'],'maxT_fwer_p_le_0_05_count':perm['maxT_fwer_p_le_0_05_count'],'conservative_signal_count':perm['conservative_permutation_signal_count'],'conservative_signals':perm['conservative_permutation_signals'],'human_reviewed':False,'automatic_morphological_analysis':False,'automatic_semantic_classification':False},
    'ameke_hostile_robustness':{'target_graphic_class':rob['target_graphic_class'],'target_proxy':rob['target_german_context_proxy'],'permutation_scheme_count':rob['permutation_scheme_count'],'permutation_test_count':rob['permutation_test_count'],'positive_p_le_0_05_test_count':rob['positive_p_le_0_05_permutation_test_count'],'all_context_schemes_p_le_0_05':rob['all_primary_context_permutation_schemes_p_le_0_05'],'all_member_binary_schemes_p_le_0_05':rob['all_member_binary_permutation_schemes_p_le_0_05'],'leave_one_target_context_min':rob['leave_one_target_member_out']['context_rate_difference_min'],'leave_one_page10_context_min':rob['leave_one_page10_block_out']['context_rate_difference_min'],'target_members_with_proxy':rob['target_signal_concentration']['target_members_with_proxy'],'target_proxy_context_count':rob['target_signal_concentration']['target_proxy_context_count'],'automatic_morphological_analysis':False,'automatic_semantic_classification':False},
    'explicit_variant_groups':var['explicit_source_variant_group_count'],'graphic_collision_groups':var['normalized_graphic_collision_group_count'],'diachronic_semantic_context_signals':sem['signal_counts'],'human_reviewed_relations':0,'warning':'Machine/documentary candidates, graphic patterns, German-context associations, mechanically stripped -ameke contrasts, permutation controls and robustness diagnostics; not validated linguistic relations, grammatical categories, meanings or morphological analyses.'}
    dump(ROOT/'public/data/research-summary.json',public);print(json.dumps(stats,ensure_ascii=False))

if __name__=='__main__':main()
