#!/usr/bin/env python3
import json
from research_common import ROOT,OUT

def main():
    s=json.loads((OUT/'corpus_research_statistics.json').read_text(encoding='utf-8')); p=ROOT/'project-metadata.json'; pm=json.loads(p.read_text(encoding='utf-8')); scope=pm.setdefault('scope',{}); pipe=pm.setdefault('editorial_pipeline',{})
    scope.update({'steffel_rar_de_unique_graphic_keys':s['rar_de_unique_graphic_keys'],'steffel_de_rar_inventory_guided_attestations':s['de_rar_inventory_guided_attestations'],'steffel_internal_concordance_candidates':s['internal_concordance_candidates'],'steffel_internal_reciprocal_german_support_candidates':s['internal_reciprocal_german_support_candidates'],'steffel_de_rar_residual_span_candidates_low_machine':s['residual_de_rar_span_candidates_low_machine'],'steffel_de_rar_residual_span_triage_candidates':s['residual_span_triage_candidates'],'steffel_de_rar_residual_span_triage_profile_class_counts':s['residual_span_triage_profile_class_counts'],'steffel_de_rar_residual_span_triage_priority_tier_counts':s['residual_span_triage_priority_tier_counts'],'steffel_explicit_source_variant_groups':s['explicit_source_variant_groups'],'steffel_normalized_graphic_collision_groups':s['normalized_graphic_collision_groups'],'diachronic_semantic_context_candidates':s['diachronic_semantic_context_candidates'],'research_layer_human_reviewed_relations':0})
    pipe.update({'internal_research_layer_generators':['scripts/generate_de_rar_attestations.py','scripts/generate_residual_span_triage.py','scripts/generate_internal_concordance.py','scripts/generate_historical_variants.py','scripts/generate_semantic_context_queue.py','scripts/generate_graphemic_statistics.py','scripts/generate_research_statistics.py'],'de_rar_inventory_guided_attestations':'data/research/de_rar_inventory_guided_attestations.json','de_rar_inventory_guided_attestations_csv':'data/research/de_rar_inventory_guided_attestations.csv','de_rar_residual_span_candidates':'data/research/de_rar_residual_span_candidates.json','de_rar_residual_span_triage':'data/research/de_rar_residual_span_triage.json','de_rar_residual_span_triage_csv':'data/research/de_rar_residual_span_triage.csv','de_rar_residual_span_triage_summary':'data/research/de_rar_residual_span_triage_summary.json','de_rar_residual_span_triage_policy':'Character n-gram profile classes prioritize inspection only; they are not automatic language identification, lexical acceptance, semantic interpretation or human validation.','steffel_internal_concordance':'data/research/internal_concordance.json','steffel_internal_concordance_csv':'data/research/internal_concordance.csv','historical_variant_index':'data/research/historical_variant_index.json','diachronic_semantic_context_queue':'data/research/diachronic_semantic_context_queue.json','diachronic_semantic_context_queue_csv':'data/research/diachronic_semantic_context_queue.csv','graphemic_statistics':'data/research/graphemic_statistics.json','corpus_research_statistics':'data/research/corpus_research_statistics.json','research_snapshot':'data/research/RESEARCH_SNAPSHOT.md','parallel_machine_research_stage':'Internal Steffel concordance, conservative residual-span profile triage, documentary variant analysis, graphemic statistics and non-adjudicative diachronic context may advance while independent human validation remains unavailable.','internal_research_non_overwrite_policy':'Derived research layers never overwrite facsimile, OCR, diplomatic transcription, PHIL history, Rarámuri Digital source records, or human-review flags.'})
    p.write_text(json.dumps(pm,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
if __name__=='__main__': main()
